// Generated by CoffeeScript 1.9.2

/*
 * Uses a Web Session to enable SteamGuard through the steam website.
#
 * When a SteamGuard code is entered, it automatically verifies the email.
 * Verified email is important for numerous bots.
#
 * @example
 * bot.use(require('vapor-verify-email'))
 * @param {Object} VaporAPI Instance of the API class.
 * @module
#
 */

(function() {
  var fs, request;

  request = require('request');

  fs = require('fs');

  exports.name = 'verify-email';

  exports.plugin = function(VaporAPI) {
    return VaporAPI.registerHandler({
      emitter: 'vapor',
      event: 'cookies'
    }, function(cookies) {
      var options;
      options = {
        url: 'https://store.steampowered.com/twofactor/manage_action',
        method: 'POST',
        form: {
          sessionid: cookies[0].split('=')[1],
          action: 'email',
          email_authenticator_check: 'on'
        },
        headers: {
          'Cookie': cookies.join("; ")
        }
      };
      return this.emit('readFile', this._sentryFile, function(err, data) {
        if (data == null) {
          return request(options, function(err, resp, body) {
            VaporAPI.emitEvent('message:info', 'Restarting to verify email.');
            VaporAPI.disconnect();
            return setTimeout(function() {
              return VaporAPI.connect();
            }, 5000);
          });
        }
      });
    });
  };

}).call(this);
